### PR TITLE
feat: Updated Remote-Robot version to 0.11.23

### LINKED ISSUE #241: feat: Update Remote-Robot framework version to 0.11.23
- newer version of Remote-Robot (0.11.23) is available, update it

### PR DESCRIPTION
**Pull request by richard0202**
Fixes #241

### CODE REVIEW

**Comment by FaiqNoman69** [comment]
> Fixes #241

**Comment by adietish** [comment]
@FaiqNoman69, @richardkocian: can you please point out why this was closed, the merge apparently refused? Thanks.

**Comment by adietish** [comment]
@lgrossma: do you know why this was closed without merging? Just asking so that I can understand the works/impediments here

**Comment by adietish** [comment]
@richardkocian thanks for pointing out.

**Pull request closed without merging**
